version: '3'

services:
    phpmyadmin:
        container_name: sf4_phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        restart: always
        ports:
            - 8191:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306

    mysql:
        container_name: sf4_mysql
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - 'db-data:/var/lib/mysql'
        restart: on-failure
        environment:
            - .env
        ports:
            - 3306:3306

    webserver:
        container_name: sf4_nginx
        image: nginx:alpine
        volumes:
            - './${PROJECT_ROOT}/public:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - 8888:80
        depends_on:
           - mysql
           - php

    php:
        container_name: sf4_website
        image: php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        user: 1000:1000
        volumes:
            - '${PROJECT_ROOT}:/usr/src/app' # must be set
        depends_on:
            - mysql
            - vue-cli

    vue-cli:
        container_name: sf4_vue_cli
        image: vue-cli
        build:
            context: .
            dockerfile: docker/vue/Dockerfile
        volumes:
            - '${PROJECT_ROOT}:/usr/src/app'
        ports:
            - "8080:8080"
        tty: true
        networks:
            - frontend

networks:
    frontend:

volumes:
    db-data: {}